basePath: /
definitions:
  dto.CreateLinkRequest:
    properties:
      original_url:
        type: string
      slug:
        type: string
      user_id:
        type: integer
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.RegisterRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - email
    - name
    - password
    type: object
  dto.Response:
    properties:
      message:
        type: string
      results: {}
      success:
        type: boolean
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      picture:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a coffee shop backend API
  title: Short Link API
  version: "1.0"
paths:
  /{slug}:
    get:
      description: Redirect user to the original URL based on slug
      parameters:
      - description: Short link slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently (Redirect)
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Redirect to original URL
      tags:
      - Redirect
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Login Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Login new user
      tags:
      - Authentication
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Register Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Register new user
      tags:
      - Authentication
  /api/links:
    post:
      consumes:
      - application/json
      description: Create a new short link for a user
      parameters:
      - description: Create Link Request
        in: body
        name: link
        required: true
        schema:
          $ref: '#/definitions/dto.CreateLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create a new short link
      tags:
      - Links
  /api/links/{id}:
    delete:
      consumes:
      - application/json
      description: Soft delete a link by ID and return updated list of links
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Soft delete a link
      tags:
      - Links
  /api/links/{user_id}:
    get:
      consumes:
      - application/json
      description: Retrieve all short links for a specific user
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get all links by user ID
      tags:
      - Links
  /users/{id}/picture:
    post:
      consumes:
      - multipart/form-data
      description: Upload a profile picture for a specific user by user ID. Max size
        1MB.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Profile picture file
        in: formData
        name: picture
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Picture uploaded successfully
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad request (invalid ID or missing/too large file)
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Upload profile picture for user
      tags:
      - Users
swagger: "2.0"
